### PR TITLE
finish the feature of tensorboard

### PR DESCRIPTION
**Pull request by YuanshengHu**
I have finish the tensorboard support

### CODE REVIEW

**Comment by manuzhang** [comment]
@YuanshengHu @tangzhankun I plan to remove calling python script in the `Client`. We can add  launching tensorboard options to `yarn-tf` and

**Comment by manuzhang** [comment]
@YuanshengHu Also, please rebase your code on the latest master with `git pull --rebase upstream master`. Commit like `Merge branch 'master' ...` shouldn't exist.

**Comment by YuanshengHu** [comment]
okay I see

**Comment by YuanshengHu** [comment]
I have already base my code on the upstream

**Comment by tangzhankun** [comment]
seems good to me. any comments @manuzhang

**Comment by manuzhang** [comment]
@tangzhankun  As I said, we'd better not manage any client script in our yarn client.

**Comment by tangzhankun** [comment]
yeah. my fault. We can just use ydf-tf to do the launch. @YuanshengHu , could you remove the launch logic from client.java and just implement in ydf0-tf script?

**Comment by YuanshengHu** [comment]
okay,I will do it

**Pull request closed without merging**
